language: java
sudo: false
install: true

cache:
  directories:
  - .autoconf
  - $HOME/.m2

script:
   - cp settings.xml ~/.m2/
   - git clone https://gerring@bitbucket.org/geneweaver/gweaver-test-data.git
   - mvn -B deploy # -B batch mode makes Maven less verbose
