language: java
sudo: false
install: true

cache:
  directories:
  - .autoconf
  - $HOME/.m2

script:
   - cp settings.xml ~/.m2/
   - git clone https://gerring@bitbucket.org/geneweaver/gweaver-test-data.git
# The bitbucket script deploys, so we just verify
#   - mvn -B deploy 
   - mvn -B verify
