# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gerring/jax:maven-3.6.3

# See https://bitbucket-pipelines.atlassian.io/validator
pipelines:
   default:
      - step:
         caches:
            - maven
            # see https://bitbucket.org/blog/cloning-another-bitbucket-repository-in-bitbucket-pipelines
         script:
            - cp settings.xml ~/.m2/
            - git clone git@bitbucket.org:geneweaver/variant-orthology-data.git
            - mvn -B deploy # -B batch mode makes Maven less verbose
            
         services:
            - docker
   
