#release configuration
#Mon Feb 22 08:37:07 GMT 2021
projectVersionPolicyId=default
scm.tagNameFormat=@{project.artifactId}-@{project.version}
exec.additionalArguments=-Dgpg.passphrase\=APBE7tu1y8nLNP8i48PgqfDEtZK
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
pushChanges=false
completedPhase=check-poms
scm.url=scm\:git\:ssh\://git@bitbucket.org\:geneweaver/gweaver-stream-io.git
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
